### ISSUE TITLE
TypeScript로 마이그레이션

### ISSUE THREAD

**Issue by dayannne** [dayannne/Market-Brick#1]
## Issue: [♻️ Refactor]
TypeScript로 마이그레이션

## Description
지금까지 작업한 컴포넌트(메인,로그인)를 TypeScript로 리팩토링

## Todo
- [x] typescript 설치
- [x] tsconfig.json 세팅
- [x] 로그인 컴포넌트 tsx로 변환 - 필요 공통컴포넌트 포함
- [x] 홈 컴포넌트 tsx로 변환

## ETC
기타사항
