### ISSUE TITLE
Header - 로그인 여부, 회원 유형 고려

### ISSUE THREAD

**Issue by dayannne** [dayannne/Market-Brick#5]
## Issue: [✨ Feat]
작업사항 이름

## Description
로그인 여부와, 로그인 시 회원 유형(구매,판매)에 따라 Header를 다르게 설정
## Todo

- [x] 로컬스토리지에서 token값, login_type 값 가져오기
- [x] 로그인 안한 상태에서는 '로그인' 버튼이 보이도록
   <img width="887" alt="image" src="https://github.com/Da-Youn/Open-Market-App/assets/105140201/c32dc2a7-e651-4965-a8e0-e2da937cfb25">

- [x] 로그인 한 상태 + 구매 회원인 경우 '마이페이지' 버튼이 보이도록
    ![image](https://github.com/Da-Youn/Open-Market-App/assets/105140201/46cd7651-cd36-4c93-aa6c-5c21e4e3f577)
- [x] 로그인 한 상태 + 판매 회원인 경우 '판매자센터' 버튼이 보이도록
   <img width="774" alt="image" src="https://github.com/Da-Youn/Open-Market-App/assets/105140201/49457454-2ee1-4a88-8792-c0fc10d77d7c">
