### ISSUE TITLE
Redux로 데이터 관리 구현

### ISSUE THREAD

**Issue by dayannne** [dayannne/Market-Brick#8]
## Issue: [✨ Feat]
Redux로 상태관리 

## Description
상품 상세 데이터, 장바구니 목록 데이터 등을 Redux로 관리하고 불러올 수 있도록 한다.
예를 들어 장바구니 목록 데이터 같은 경우 여러 컴포넌트에서 쓰이고 있는데,
Redux로 세팅해 두면 컴포넌트마다 일일이 API요청을 하지 않고도 데이터를 불러오며 관리할 수 있다.

## Todo
1. [x] 1. store.tsx 세팅하기 (configureStore)
2. '~Slice'라는 이름의 reducer 파일 만들기
3.  useSelector와 useDispatch를 사용해 데이터 dispatch 후 불러오기
- [x] 상품 상세 데이터
- [x] 장바구니 목록 데이터
- [x] (추가 예정)
